version: "3.9"  # optional since v1.27.0
services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_DB_CONNECTION_STRING=mongodb+srv://vielm18_student:QGj8mKgXG8jowevO@cluster0.taqiyox.mongodb.net/?retryWrites=true&w=majority
      - MONGO_DB_NAME=Cluster0
      - REDIS_URI=rediss://default:AVNS_QSAOpz7BFPdxEYVvQK3@redis-eee405d-tempestistheone-c875.aivencloud.com:19727
      